sudo: false
dist: trusty
language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@5
  - npm i -g typescript
  - npm i -g webpack
install:
  - npm install
services:
  - mongodb
